export interface IdeaData {
  id: string | number;
  campaign_id: number;
  campaign_groupid: number;
  campaign_ideacount: number;
  campaign_name: string;
  campaign_expiry_date: string; // ISO format timestamp
  requested_fund: number;
  requested_fund_usd: number;
  project_duration: number;
  opensource: boolean;
  fund: string;
  fund_no: number;
  title: string;
  idea_number: number;
  description: string;
  funnel_id: number;
  co_submitters: string;
  subscribed: boolean;
  moderate: boolean;
  member_action_allowed: boolean;
  comment_count: number;
  kudo_count: number;
  owner_count: number;
  kudo_given: boolean;
  labels: string;
  render_format: number;
  kudos_allowed: boolean;
  commenting_allowed: boolean;
  commenting_enabled: boolean;
  following_enabled: boolean;
  following_idea_author: boolean;
  assignment_text: string;
  pinned: boolean;
  summarized: boolean;
  draft: boolean;
  sharable: boolean;
  email_idea_allowed: boolean;
  created_at: string; // ISO format timestamp
  linked_ideas: string;
  file_attachment_allowed: boolean;
  edit_idea_allowed: boolean;
  followers_count: number;
  tickets: string;
  idea_view_count: number;
  revision_history_count: number;
  default_tab: string;
  last_edited_at: string | null; // ISO timestamp or null
  seen: boolean;
  build_team_view_allowed: boolean;
  custom_description_label: string;
  custom_attachments: string;
  comment_attachments: string;
  attachments: string;
  submitter_id: number;
  submitter_name: string;
  submitter_username: string;
  submitter_following: boolean;
  submitter_avatar: string;
  submitter_identity_hidden: boolean;
  translation_translated: boolean;
  allowedmedialist: string;
  fieldsections: string;
  ideatagholder: string;
  supercommentsholder: string;
  commentoptionsholder: string;
  lasteditedby_username: string;
  source_file: string;
  processed_at: string | null; // ISO timestamp or null
}
